# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c3a0289f-845a-458b-a6a3-6298df9ebdce";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."nixos".device = "/dev/disk/by-uuid/4ebfda9d-e260-49d0-af51-b05c8456d97b";

  fileSystems."/snapshots" =
    { device = "/dev/disk/by-uuid/c3a0289f-845a-458b-a6a3-6298df9ebdce";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/persistent" =
    { device = "/dev/disk/by-uuid/c3a0289f-845a-458b-a6a3-6298df9ebdce";
      fsType = "btrfs";
      options = [ "subvol=@persistent" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/c3a0289f-845a-458b-a6a3-6298df9ebdce";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/c3a0289f-845a-458b-a6a3-6298df9ebdce";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CF1D-AE34";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0f4u1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
